# See https://www.netlifycms.org/docs/configuration-options for config details.
#
# Set `backend:name:` to `test-repo` to test the CMS UI. 
#
# Remember to switch `backend:name:` back to `git-gateway` before doing a git commit!

backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://gdscupd.com"

collections:
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "posts/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["title", "date", dateEnd"]
    fields:
      - {
          name: "title",
          label: "Title",
          widget: "string",
        }
      - {
          name: "date",
          label: "Start",
          widget: "datetime",
        }
      - {
          name: "dateEnd",
          label: "End",
          widget: "datetime",
        }
      - {
          name: "eventType",
          label: "type",
          widget: "select",
          options: ["Speaker Sessions", "Internal", "Workshops", "Tech Solutions"],
        }
      - {
          name: "location",
          label: "Location",
          widget: "string",
        }
      - {
          name: "locationURL",
          label: "URL",
          widget: "string",
        }
      - {
          name: "images",
          label: "Images",
          label_singular: "image",
          widget: "list",
          summary: "{{fields.image}}",
          field: { name: "image", label: "Image", widget: "image", },
        }
      - {
          name: "summary",
          label: "Summary",
          widget: "text",
        }
      - {
          name: "body",
          label: "Body",
          widget: "markdown",
          minimal: true,
        }

  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "posts/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["title"]
    fields:
      - {
          name: "title",
          label: "Title",
          widget: "string",
        }
      - {
          name: "thumbnail",
          label: "Thumbnail",
          widget: "image",
        }
      - {
          name: "images",
          label: "Images",
          label_singular: "image",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image", },
        }
      - {
          name: "body",
          label: "Body",
          widget: "markdown",
          minimal: true,
        }

  - name: "members"
    label: "Members"
    label_singular: "Member"
    folder: "posts/members"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    sortable_fields: ["name"]
    view_groups: 
      - label: Team
        field: team
    fields:
      - {
          name: "name",
          label: "Name",
          widget: "string",
        }
      - {
          name: "team",
          label: "Team",
          widget: "select",
          options:
                  [
                    "Executive",
                    "Technology",
                    "Operations",
                    "Communications",
                    "Finance and Externals",
                    "Web Development",
                  ],
        }
      - {
          name: "position",
          label: "Position",
          widget: "string",
        }
      - {
          name: "thumbnail",
          label: "Thumbnail",
          widget: "image",
        }
      - {
          name: "quote",
          label: "Quote",
          widget: "string",
        }
      - {
          name: "facebookURL",
          label: "Facebook URL",
          widget: "string",
          required: false,
        }
      - {
          name: "twitterURL",
          label: "Twitter URL",
          widget: "string",
          required: false,
        }
      - {
          name: "linkedinURL",
          label: "LinkedIn URL",
          widget: "string",
          required: false,
        }
      - {
          name: "githubURL",
          label: "GitHub URL",
          widget: "string",
          required: false,
        }
      - {
          name: "body",
          label: "Body",
          widget: "markdown",
          minimal: true,
        }
