backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Event" # Used in the UI
    folder: "posts/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start Date Time", name: "date", widget: "datetime" }
      - { label: "End Date Time", name: "dateEnd", widget: "datetime" }
      - {
          label: "Event type",
          name: "eventType",
          widget: "select",
          options:
            ["Speaker Sessions", "Study Jams", "Workshops", "Tech Solutions"],
        }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Location URL", name: "locationURL", widget: "string" }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - {
          label: "Summary",
          name: "summary",
          widget: "text",
          hint: "Recommended to use a maximum of 115 characters",
        }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "posts/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "exec"
    label: "Executive Members"
    folder: "posts/exec"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Quote", name: "quote", widget: "string" }
      - { label: "Facebook URL", name: "facebookURL", widget: "string", required: false }
      - { label: "Twitter URL", name: "twitterURL", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedinURL", widget: "string", required: false }
      - { label: "GitHub URL", name: "githubURL", widget: "string", required: false }


  - name: "tech"
    label: "Technology Members"
    folder: "posts/tech"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Quote", name: "quote", widget: "string" }
      - { label: "Facebook URL", name: "facebookURL", widget: "string", required: false }
      - { label: "Twitter URL", name: "twitterURL", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedinURL", widget: "string", required: false }
      - { label: "GitHub URL", name: "githubURL", widget: "string", required: false }


  - name: "ops"
    label: "Operations Members"
    folder: "posts/ops"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Quote", name: "quote", widget: "string" }
      - { label: "Facebook URL", name: "facebookURL", widget: "string", required: false }
      - { label: "Twitter URL", name: "twitterURL", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedinURL", widget: "string", required: false }
      - { label: "GitHub URL", name: "githubURL", widget: "string", required: false }


  - name: "comms"
    label: "Communications Members"
    folder: "posts/comms"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Quote", name: "quote", widget: "string" }
      - { label: "Facebook URL", name: "facebookURL", widget: "string", required: false }
      - { label: "Twitter URL", name: "twitterURL", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedinURL", widget: "string", required: false }
      - { label: "GitHub URL", name: "githubURL", widget: "string", required: false }


  - name: "extefin"
    label: "Externals and Finance Members"
    folder: "posts/extefin"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Quote", name: "quote", widget: "string" }
      - { label: "Facebook URL", name: "facebookURL", widget: "string", required: false }
      - { label: "Twitter URL", name: "twitterURL", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedinURL", widget: "string", required: false }
      - { label: "GitHub URL", name: "githubURL", widget: "string", required: false }

      