backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Event" # Used in the UI
    folder: "posts/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start Date Time", name: "date", widget: "datetime" }
      - { label: "End Date Time", name: "dateEnd", widget: "datetime" }
      - {
          label: "Event type",
          name: "eventType",
          widget: "select",
          options:
            ["Speaker Sessions", "Study Jams", "Workshops", "Tech Solutions"],
        }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Location URL", name: "locationURL", widget: "string" }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "posts/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
